# Generated by Django 4.2.5 on 2023-09-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('hash', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='quesBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('seconded', models.IntegerField(default=0)),
                ('disliked', models.IntegerField(default=0)),
                ('studentID', models.IntegerField()),
                ('submitTime', models.DateTimeField(auto_now_add=True)),
                ('finalscore', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='quesDislikeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesID', models.IntegerField()),
                ('studentID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='quesResponseDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesID', models.IntegerField()),
                ('response', models.TextField()),
                ('responderType', models.CharField(choices=[('A', 'admin'), ('S', 'student')], max_length=1)),
                ('responderID', models.IntegerField()),
                ('respondTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='quesSecondDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesID', models.IntegerField()),
                ('studentID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stuBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('hash', models.CharField(max_length=10)),
            ],
        ),
    ]
