# Generated by Django 4.2.5 on 2023-10-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dataSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quesEvaluateDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesID', models.IntegerField()),
                ('studentID', models.IntegerField()),
                ('evaluate', models.CharField(choices=[('S', 'seconded'), ('N', 'none'), ('D', 'dislike')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='quesDislikeDB',
        ),
        migrations.DeleteModel(
            name='quesSecondDB',
        ),
    ]
