# Generated by Django 4.2.5 on 2023-10-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_dataSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesbaseinfo',
            old_name='adminsuconded',
            new_name='adminseconded',
        ),
    ]
