# Generated by Django 4.2.5 on 2023-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dataSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesbaseinfo',
            name='admindisliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quesbaseinfo',
            name='adminsuconded',
            field=models.BooleanField(default=False),
        ),
    ]
