# Generated by Django 4.2.5 on 2023-10-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dataSystem', '0002_quesevaluatedb_delete_quesdislikedb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesevaluatedb',
            name='evaluate',
            field=models.CharField(choices=[('S', 'seconded'), ('N', 'none'), ('D', 'dislike')], default='N', max_length=1),
        ),
    ]
