# Generated by Django 4.2.5 on 2023-10-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dataSystem', '0002_quesbaseinfo_admindisliked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesbaseinfo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
