# Generated by Django 6.1.1 on 2026-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dataSystem', '0002_userprofile_delete_adminbaseinfo_delete_stubaseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesbaseinfo',
            name='studentID',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quesbaseinfo',
            name='week',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quesevaluatedb',
            name='quesID',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quesevaluatedb',
            name='studentID',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quesresponsedb',
            name='quesID',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quesresponsedb',
            name='responderID',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quesresponsedb',
            name='week',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weekdb',
            name='week',
            field=models.IntegerField(unique=True),
        ),
    ]
